// scripts/legacyPrintReferenceImport/buildReferenceDrumDataset.mjs

import fs from 'node:fs/promises';

import path from 'node:path';

import { fileURLToPath } from 'node:url';

import { normalizeReferenceDrumRecords } from './normalizeReferenceDrums.mjs';

import { validateReferenceDrumRecords } from './validateReferenceDrums.mjs';

const __filename = fileURLToPath(import.meta.url);

const __dirname = path.dirname(__filename);

const SOURCES_DIR = path.join(__dirname, 'sources');

const OUTPUT_DIR = path.join(

  __dirname,

  '../../src/data/legacyPrint/referenceDrums/generated'

);

const OUTPUT_JSON_PATH = path.join(OUTPUT_DIR, 'referenceDrumDataset.json');

const OUTPUT_JS_PATH = path.join(OUTPUT_DIR, 'referenceDrumDataset.js');

const OUTPUT_REPORT_PATH = path.join(OUTPUT_DIR, 'referenceDrumDatasetReport.json');

const readJsonFile = async (filePath) => {

  const raw = await fs.readFile(filePath, 'utf8');

  return JSON.parse(raw);

};

const getSourceJsonFiles = async () => {

  const entries = await fs.readdir(SOURCES_DIR, {

    withFileTypes: true,

  });

  return entries

    .filter((entry) => entry.isFile())

    .filter((entry) => entry.name.endsWith('.json'))

    .map((entry) => path.join(SOURCES_DIR, entry.name));

};

const buildDataset = async () => {

  const sourceFiles = await getSourceJsonFiles();

  const rawRecordsByFile = await Promise.all(

    sourceFiles.map(async (filePath) => {

      const records = await readJsonFile(filePath);

      if (!Array.isArray(records)) {

        throw new Error(`${filePath} must export a JSON array.`);

      }

      return records.map((record) => ({

        ...record,

        importSourceFile: path.basename(filePath),

      }));

    })

  );

  const rawRecords = rawRecordsByFile.flat();

  const normalizedRecords = normalizeReferenceDrumRecords(rawRecords);

  const validationResults = validateReferenceDrumRecords(normalizedRecords);

  const invalidRecords = validationResults.filter((result) => !result.isValid);

  const warningRecords = validationResults.filter(

    (result) => result.warnings.length > 0

  );

  await fs.mkdir(OUTPUT_DIR, {

    recursive: true,

  });

  await fs.writeFile(

    OUTPUT_JSON_PATH,

    JSON.stringify(normalizedRecords, null, 2)

  );

  await fs.writeFile(

    OUTPUT_JS_PATH,

    `// Auto-generated by scripts/legacyPrintReferenceImport/buildReferenceDrumDataset.mjs\n\nexport const referenceDrumDataset = ${JSON.stringify(

      normalizedRecords,

      null,

      2

    )};\n`

  );

  await fs.writeFile(

    OUTPUT_REPORT_PATH,

    JSON.stringify(

      {

        generatedAt: new Date().toISOString(),

        sourceFiles: sourceFiles.map((filePath) => path.basename(filePath)),

        totalRecords: normalizedRecords.length,

        validRecords: validationResults.filter((result) => result.isValid)

          .length,

        invalidRecords,

        warningRecords,

      },

      null,

      2

    )

  );

  console.log('LegacyPrint reference drum dataset built.');

  console.log(`Source files: ${sourceFiles.length}`);

  console.log(`Total records: ${normalizedRecords.length}`);

  console.log(`Invalid records: ${invalidRecords.length}`);

  console.log(`Warnings: ${warningRecords.length}`);

  if (invalidRecords.length) {

    console.error(JSON.stringify(invalidRecords, null, 2));

    process.exitCode = 1;

  }

};

buildDataset().catch((error) => {

  console.error(error);

  process.exit(1);

});